#!/usr/bin/env python3
"""Compile, run and check every example in the cooljava collection.

Fenced block conventions (the first word of the info string is the language):

  ```java run [jdk=N] [args="..."] [stderr] [exit=N] [timeout=S] [nondeterministic] [file=Name.java]
      A complete program. It is launched with the source launcher
      (`java Name.java`) and its stdout must match the next ```text output block.
  ```java preview [same options]
      Same as `run`, but on JDK 27 with --enable-preview --source 27.
  ```java compile-fail [jdk=N] [args="..."] [file=Name.java]
      Must be rejected by javac. The next ```text compile-error block (if any)
      holds the real compiler message.
  ```text output / ```text compile-error
      Generated by `--update` from real runs. Never typed by hand.

Plain ```java blocks are fragments and are not checked.

Usage:
  python3 tools/verify.py                  # verify every doc
  python3 tools/verify.py 01-functional/001-maybe-monad.md
  python3 tools/verify.py --update FILE    # rewrite output blocks from real runs
  python3 tools/verify.py --since FILE     # also check the "Since: Java N" badge with javac --release N

JDKs are found through JDK25_HOME, JDK27_HOME (or JDK<N>_HOME for any N).
"""
import argparse
import os
import re
import shlex
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_JDK = 25
PREVIEW_JDK = 27
FENCE = re.compile(r"^```(.*)$")
TOP_LEVEL_TYPE = re.compile(
    r"^(?:(?:public|final|abstract|sealed|non-sealed|strictfp|static)\s+)*"
    r"(?:class|interface|enum|record|@interface)\s+([A-Za-z_$][\w$]*)"
)
SINCE = re.compile(r"\*\*Since:\*\*\s*Java\s+(\d+)")


def jdk_home(version):
    home = os.environ.get(f"JDK{version}_HOME")
    if home and Path(home, "bin", "java").exists():
        return Path(home)
    candidates = [os.environ.get("JAVA_HOME")]
    java = shutil.which("java")
    if java:
        candidates.append(str(Path(java).resolve().parent.parent))
    for home in filter(None, candidates):
        exe = Path(home, "bin", "java")
        if exe.exists():
            p = subprocess.run([str(exe), "-version"], capture_output=True, text=True)
            m = re.search(r'version "(\d+)', p.stderr)
            if m and int(m.group(1)) == version:
                return Path(home)
    sys.exit(f"No JDK {version} found. Set JDK{version}_HOME (or JAVA_HOME) to a JDK {version} installation.")


class Block:
    def __init__(self, info, start, end, lines):
        self.info = info.strip()
        self.start = start  # index of the opening fence line
        self.end = end  # index of the closing fence line
        self.code = "\n".join(lines)
        parts = shlex.split(self.info) if self.info else []
        self.lang = parts[0] if parts else ""
        self.flags = set()
        self.opts = {}
        for p in parts[1:]:
            if "=" in p:
                k, v = p.split("=", 1)
                self.opts[k] = v
            else:
                self.flags.add(p)

    @property
    def kind(self):
        if self.lang == "java":
            for k in ("run", "preview", "compile-fail"):
                if k in self.flags:
                    return k
        if self.lang == "text":
            for k in ("output", "compile-error"):
                if k in self.flags:
                    return k
        return None


def parse_blocks(lines):
    blocks, i = [], 0
    while i < len(lines):
        m = FENCE.match(lines[i])
        if m and m.group(1).strip() != "":
            j = i + 1
            while j < len(lines) and lines[j].rstrip() != "```":
                j += 1
            blocks.append(Block(m.group(1), i, j, lines[i + 1 : j]))
            i = j + 1
        elif m:
            # anonymous fence, skip to its end
            j = i + 1
            while j < len(lines) and lines[j].rstrip() != "```":
                j += 1
            i = j + 1
        else:
            i += 1
    return blocks


def file_name_for(block):
    if "file" in block.opts:
        return block.opts["file"]
    current = None
    for line in block.code.splitlines():
        m = TOP_LEVEL_TYPE.match(line)
        if m:
            current = m.group(1)
        if re.search(r"\bvoid\s+main\s*\(", line):
            if re.match(r"^\S", line):  # top-level main: compact source file
                return "Main.java"
            return f"{current or 'Main'}.java"
    return f"{current or 'Main'}.java"


def normalize(text, tmp):
    if tmp:
        text = text.replace(str(tmp) + os.sep, "").replace(str(tmp), "")
    lines = [l.rstrip() for l in text.replace("\r\n", "\n").split("\n")]
    while lines and lines[-1] == "":
        lines.pop()
    while lines and lines[0] == "":
        lines.pop(0)
    return "\n".join(lines)


def block_jdk(block):
    if block.kind == "preview":
        return int(block.opts.get("jdk", PREVIEW_JDK))
    return int(block.opts.get("jdk", DEFAULT_JDK))


def block_args(block, version, launcher):
    args = shlex.split(block.opts.get("args", ""))
    if block.kind == "preview" and "--enable-preview" not in args:
        args.insert(0, "--enable-preview")
    if "--enable-preview" in args:
        flag = "--source" if launcher else "--release"
        if flag not in args:
            args += [flag, str(version)]
    return args


def run_block(block):
    version = block_jdk(block)
    java = jdk_home(version) / "bin" / "java"
    tmp = Path(tempfile.mkdtemp(prefix="cooljava-"))
    try:
        src = tmp / file_name_for(block)
        src.write_text(block.code + "\n")
        cmd = [str(java), *block_args(block, version, True), src.name]
        timeout = int(block.opts.get("timeout", 120))
        try:
            p = subprocess.run(
                cmd, cwd=tmp, capture_output=True, text=True, timeout=timeout
            )
        except subprocess.TimeoutExpired:
            return None, f"timed out after {timeout}s", None
        out = p.stdout + (p.stderr if "stderr" in block.flags else "")
        expected_exit = int(block.opts.get("exit", 0))
        err = None
        if p.returncode != expected_exit:
            err = f"exit code {p.returncode}, expected {expected_exit}\n{p.stderr[-3000:]}"
        return normalize(out, tmp), err, normalize(p.stderr, tmp)
    finally:
        shutil.rmtree(tmp, ignore_errors=True)


def compile_block(block, release=None, preview=False):
    """Returns (ok, compiler output)."""
    version = block_jdk(block)
    if release and release > DEFAULT_JDK:
        version = max(version, release)
    javac = jdk_home(version) / "bin" / "javac"
    tmp = Path(tempfile.mkdtemp(prefix="cooljava-"))
    try:
        src = tmp / file_name_for(block)
        src.write_text(block.code + "\n")
        args = [a for a in shlex.split(block.opts.get("args", ""))]
        # launcher only flags are not javac flags
        clean, skip = [], False
        for a in args:
            if skip:
                skip = False
                continue
            if a in ("--add-opens", "--add-exports-private"):
                skip = True
                continue
            if a.startswith("--add-opens=") or a.startswith("--enable-native-access") or a.startswith("-X") or a.startswith("-D") or a.startswith("-XX"):
                continue
            clean.append(a)
        if preview or block.kind == "preview":
            clean = [a for a in clean if a != "--enable-preview"]
            clean += ["--enable-preview", "--release", str(version)]
        elif release:
            clean += ["--release", str(release)]
        cmd = [str(javac), "-d", str(tmp / "out"), "-Xlint:none", *clean, src.name]
        p = subprocess.run(cmd, cwd=tmp, capture_output=True, text=True, timeout=120)
        return p.returncode == 0, normalize(p.stdout + p.stderr, tmp)
    finally:
        shutil.rmtree(tmp, ignore_errors=True)


def next_block(blocks, idx, kind):
    for b in blocks[idx + 1 :]:
        if b.kind == kind:
            return b
        if b.kind in ("run", "preview", "compile-fail"):
            return None
    return None


def verify_file(path, update, since_check):
    lines = path.read_text().split("\n")
    blocks = parse_blocks(lines)
    problems, notes, replacements = [], [], []
    checked = 0
    for idx, b in enumerate(blocks):
        if b.kind in ("run", "preview"):
            checked += 1
            out, err, _ = run_block(b)
            if err:
                problems.append(f"line {b.start + 1}: {err}")
                continue
            target = next_block(blocks, idx, "output")
            if target is None:
                problems.append(f"line {b.start + 1}: run block has no ```text output block")
                continue
            if update:
                replacements.append((target, out))
            elif "nondeterministic" in b.flags:
                pass
            elif normalize(target.code, None) != out:
                problems.append(
                    f"line {b.start + 1}: output differs\n--- expected\n{target.code}\n--- actual\n{out}"
                )
        elif b.kind == "compile-fail":
            checked += 1
            ok, msg = compile_block(b)
            if ok:
                problems.append(f"line {b.start + 1}: compile-fail block compiled fine")
                continue
            target = next_block(blocks, idx, "compile-error")
            if target is not None:
                if update:
                    replacements.append((target, msg))
                elif normalize(target.code, None) != msg:
                    problems.append(
                        f"line {b.start + 1}: compiler message differs\n--- expected\n{target.code}\n--- actual\n{msg}"
                    )
    runnable = [b for b in blocks if b.kind in ("run", "preview")]
    if since_check:
        m = SINCE.search("\n".join(lines))
        if not m:
            problems.append("no **Since:** Java N badge found")
        else:
            n = int(m.group(1))
            for b in runnable:
                if b.kind == "preview":
                    continue
                ok, msg = compile_block(b, release=n)
                if not ok:
                    problems.append(f"line {b.start + 1}: does not compile with --release {n}\n{msg}")
            if runnable and n > 8 and all(b.kind == "run" for b in runnable):
                if all(compile_block(b, release=n - 1)[0] for b in runnable):
                    notes.append(f"run blocks also compile with --release {n - 1}; is 'Since: Java {n}' right?")
    if update and replacements:
        for target, text in sorted(replacements, key=lambda r: r[0].start, reverse=True):
            lines[target.start + 1 : target.end] = text.split("\n") if text else []
        path.write_text("\n".join(lines))
    return checked, problems, notes


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("files", nargs="*")
    ap.add_argument("--update", action="store_true", help="rewrite output blocks from real runs")
    ap.add_argument("--since", action="store_true", help="check the Since badge with javac --release")
    a = ap.parse_args()
    files = [Path(f).resolve() for f in a.files] or sorted(ROOT.glob("[0-9][0-9]-*/[0-9][0-9][0-9]-*.md"))
    total_checked, failed = 0, 0
    for f in files:
        checked, problems, notes = verify_file(f, a.update, a.since)
        total_checked += checked
        rel = f.relative_to(ROOT) if f.is_relative_to(ROOT) else f
        status = "FAIL" if problems else ("ok  " if checked else "skip")
        print(f"{status} {rel} ({checked} checked block{'s' if checked != 1 else ''})")
        for p in problems:
            print("     " + p.replace("\n", "\n     "))
        for n in notes:
            print("     note: " + n)
        failed += bool(problems)
    print(f"\n{len(files)} docs, {total_checked} blocks checked, {failed} docs failing")
    sys.exit(1 if failed else 0)


if __name__ == "__main__":
    main()
